### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by almereyda** [ec-melodies/demo-portal#20]
Most, if not all, of the linked resources which can be added to the Workspace are served via HTTP, whilst the site itself is hosted via HTTPS.

Thus all requests from insecure locations are blocked due to CORS protection.

**Comment by letmaik** [comment]
The site is not hosted via HTTPS (at least that's not the URL we list on the repo docs etc). Any chance you use the HTTPS Everywhere addon for your browser?

**Comment by almereyda** [comment]
Sincerely I had deactivated it, but the behaviour I received looks as I hadn't. Now the issue is gone in my local environment and I can use the regular HTTP URL.
